version: '3'
services:
  app:
    build: .
    container_name: myapp
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  mongo:
    image: mongo:4.2
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
volumes:
  mongodb_data: