version: '3'
services:
  app:
    image: node:14
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: bash -c "npm install && npx nodemon server.js"
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  mongo:
    image: mongo:4.2
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
volumes:
  mongodb_data: